apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: devops
  labels:
    app: sonarqube
spec:
  # Utilisation de NodePort pour que le service soit accessible depuis l'extérieur du cluster (via Minikube)
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000       # Port du service Kubernetes (utilisé par Jenkins)
      targetPort: 9000 # Port sur le Pod SonarQube (l'application elle-même)